In [2]:
import numpy as np

# elements have to be the same dtype (n-dimensional array)

np1 = np.array([1, 2, 3])
np1.shape

(3,)

In [3]:
print(np.arange(0, 10, 2))
print(np.zeros(10))
print(np.full((10), 5))
print(np.zeros((2, 10)))
print(np.full((2, 3), 8))

[0 2 4 6 8]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[5 5 5 5 5 5 5 5 5 5]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[8 8 8]
 [8 8 8]]


In [4]:
listy = [1, 2, 3, 4, 5]
converted = np.array(listy)
print(converted)
print(converted[0])
print(converted[3])
x = np.zeros((3, 5, 2))
print(x)
print(x.shape)


[1 2 3 4 5]
1
4
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
(3, 5, 2)


In [5]:
x = np.arange(10)
print(x)
print(x[0:5])
print(x[1:2])
print(x[1:])
print(x[:8])
print(x[:])
print(x[-1:])
print(x[-3:-1])
print(x[0:8:2])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[1]
[1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7]
[0 1 2 3 4 5 6 7 8 9]
[9]
[7 8]
[0 2 4 6]


In [6]:
x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(x)
print(x[1, 2])
print(x[0, 2])
print(x[0:, 4])
print(x[0, 1:4])
print(x[0:, 0])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
8
3
[ 5 10]
[2 3 4]
[1 6]


In [7]:
x = np.arange(0, 10, 2)
print(x)
for a in np.sqrt(x):
    print(a)
print("==========================================")
print(np.sqrt(x[2]))
x = np.arange(-10, 0, 2)
print(x)
print(np.absolute(x))
x = np.array([1, 2, 3])
print(np.exp(x[0]))
print(np.exp(x))
print(np.min(x))
print(np.max(x))
x = np.array([-1, -2, 3, 4, 5, -6, -10, 0])
print(np.sign(x))
print(np.sin(x))
x = np.arange(1, 10)
print(np.log(x))

[0 2 4 6 8]
0.0
1.4142135623730951
2.0
2.449489742783178
2.8284271247461903
2.0
[-10  -8  -6  -4  -2]
[10  8  6  4  2]
2.718281828459045
[ 2.71828183  7.3890561  20.08553692]
1
3
[-1 -1  1  1  1 -1 -1  0]
[-0.84147098 -0.90929743  0.14112001 -0.7568025  -0.95892427  0.2794155
  0.54402111  0.        ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [8]:
x = np.arange(10)
print(x)
# deep (copy) and shallow (view) copy concept
x2 = x.view()
print(f"x: {x}\nx2: {x2}")
x2[0] = 234
print(f"x: {x}\nx2: {x2}")
x3 = x.copy()
print("==========================================")
print(f"x: {x}\nx3: {x3}")
x3[0] = 0
print(f"x: {x}\nx3: {x3}")
print("==========================================")
x = np.arange(10)
x2 = x.view()
x3 = x.copy()
print(f"original: {x}\nview: {x2}\ncopy: {x3}")
x[0] = 42
print(f"original: {x}\nview: {x2}\ncopy: {x3}")

[0 1 2 3 4 5 6 7 8 9]
x: [0 1 2 3 4 5 6 7 8 9]
x2: [0 1 2 3 4 5 6 7 8 9]
x: [234   1   2   3   4   5   6   7   8   9]
x2: [234   1   2   3   4   5   6   7   8   9]
x: [234   1   2   3   4   5   6   7   8   9]
x3: [234   1   2   3   4   5   6   7   8   9]
x: [234   1   2   3   4   5   6   7   8   9]
x3: [0 1 2 3 4 5 6 7 8 9]
original: [0 1 2 3 4 5 6 7 8 9]
view: [0 1 2 3 4 5 6 7 8 9]
copy: [0 1 2 3 4 5 6 7 8 9]
original: [42  1  2  3  4  5  6  7  8  9]
view: [42  1  2  3  4  5  6  7  8  9]
copy: [0 1 2 3 4 5 6 7 8 9]


In [9]:
x = np.arange(10)
print(x.shape)
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x.shape)
x = np.arange(10)
x2 = x.reshape(2, 5)
print(x2)
print("==========================================")
print(x.reshape(5, 2))
x = np.arange(12)
print(x.reshape(3, 2, 2))
print("==========================================")
x = np.arange(20)
print(x.reshape(5, 2, 2))
print("==========================================")
y = x.reshape(5, 2, 2)
print(y)
print(y.reshape(-1))

(10,)
(2, 3)
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [10]:
x = np.arange(30)
y = x.reshape(5, 3, 2)
for i, a in enumerate(y):
    print(f"element No. {i + 1}")
    print("==========================================")
    for j, b in enumerate(a):
        print(f"row No. {j + 1}")
        for k, c in enumerate(b):
            print(f"value No. {k + 1} AND value is: {c}")

element No. 1
row No. 1
value No. 1 AND value is: 0
value No. 2 AND value is: 1
row No. 2
value No. 1 AND value is: 2
value No. 2 AND value is: 3
row No. 3
value No. 1 AND value is: 4
value No. 2 AND value is: 5
element No. 2
row No. 1
value No. 1 AND value is: 6
value No. 2 AND value is: 7
row No. 2
value No. 1 AND value is: 8
value No. 2 AND value is: 9
row No. 3
value No. 1 AND value is: 10
value No. 2 AND value is: 11
element No. 3
row No. 1
value No. 1 AND value is: 12
value No. 2 AND value is: 13
row No. 2
value No. 1 AND value is: 14
value No. 2 AND value is: 15
row No. 3
value No. 1 AND value is: 16
value No. 2 AND value is: 17
element No. 4
row No. 1
value No. 1 AND value is: 18
value No. 2 AND value is: 19
row No. 2
value No. 1 AND value is: 20
value No. 2 AND value is: 21
row No. 3
value No. 1 AND value is: 22
value No. 2 AND value is: 23
element No. 5
row No. 1
value No. 1 AND value is: 24
value No. 2 AND value is: 25
row No. 2
value No. 1 AND value is: 26
value No. 2 AND v

In [11]:
x = np.arange(4)
for a in x:
    print(a)
print("==========================================")
y = x.reshape(2, 2)
for a in y:
    for b in a:
        print(b)
print("==========================================")
for a in y:
    print(a)

0
1
2
3
0
1
2
3
[0 1]
[2 3]


In [12]:
x = np.arange(15)
y = x.reshape(3, 5, 1)
print(y)
print("==========================================")
for a in np.nditer(y):
    print(a)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]
  [13]
  [14]]]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [13]:
x = np.arange(-10, -1)
x = np.absolute(x)
print(x)
print(np.sort(x))
x = np.array(["alpha", "charlie", "delta", "bravo"])
print(x)
print(np.sort(x))
x = np.array([True, False, False, False, True])
print(x)
print(np.sort(x))

[10  9  8  7  6  5  4  3  2]
[ 2  3  4  5  6  7  8  9 10]
['alpha' 'charlie' 'delta' 'bravo']
['alpha' 'bravo' 'charlie' 'delta']
[ True False False False  True]
[False False False  True  True]


In [14]:
x = np.arange(-10, 0)
x = np.absolute(x)
print(x)
x = x.reshape(2, 5)
print(x)
print(np.sort(x))
x = np.arange(-30, 0)
x = np.absolute(x)
x = x.reshape(5, 3, 2)
print("==========================================")
print(x)
print("==========================================")
print(np.sort(x))

[10  9  8  7  6  5  4  3  2  1]
[[10  9  8  7  6]
 [ 5  4  3  2  1]]
[[ 6  7  8  9 10]
 [ 1  2  3  4  5]]
[[[30 29]
  [28 27]
  [26 25]]

 [[24 23]
  [22 21]
  [20 19]]

 [[18 17]
  [16 15]
  [14 13]]

 [[12 11]
  [10  9]
  [ 8  7]]

 [[ 6  5]
  [ 4  3]
  [ 2  1]]]
[[[29 30]
  [27 28]
  [25 26]]

 [[23 24]
  [21 22]
  [19 20]]

 [[17 18]
  [15 16]
  [13 14]]

 [[11 12]
  [ 9 10]
  [ 7  8]]

 [[ 5  6]
  [ 3  4]
  [ 1  2]]]


In [15]:
x = np.arange(10)
x = np.append(x, [11, 3, 2, 4, 1, 1, 1, 1, 12, 42])
print(x)
print(np.where(x == 1))
ones = np.where(x == 1)
print(ones)
print(x[ones])
print(np.where(x % 2 == 0))
for a in x[np.where(x % 2 == 0)]:
    print(a)
print("==========================================")
x = x.reshape(2, 5, 2)
print(x)
print(np.where(x == 1))

[ 0  1  2  3  4  5  6  7  8  9 11  3  2  4  1  1  1  1 12 42]
(array([ 1, 14, 15, 16, 17]),)
(array([ 1, 14, 15, 16, 17]),)
[1 1 1 1 1]
(array([ 0,  2,  4,  6,  8, 12, 13, 18, 19]),)
0
2
4
6
8
2
4
12
42
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[11  3]
  [ 2  4]
  [ 1  1]
  [ 1  1]
  [12 42]]]
(array([0, 1, 1, 1, 1]), array([0, 2, 2, 3, 3]), array([1, 0, 1, 0, 1]))


In [16]:
x = np.array([1, 2, 3, 4])
filtery = np.array([True, False, True * 2])
print(filtery)
print(x[filtery])  # fancy indexing

[1 0 2]
[2 1 3]


In [17]:
# Option 1: List each value explicitly
filtery = np.array([True, False, True, True])
print(x[filtery])
# Option 2: Use concatenation if you need a shorthand
filtery = np.array([True, False] + [True] * 2)
x = np.array([1, 2, 3, 4])
print(x[filtery])

[1 3 4]
[1 3 4]


In [19]:
x = np.arange(10)
filtered = x % 2 == 0
print(x[filtered])
filtered = x > 5
print(x[filtered])


[0 2 4 6 8]
[6 7 8 9]
